PharmacyManagementSystem/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PharmacyManagementSystem.Models;

namespace PharmacyManagementSystem.Controllers
{
    public class OrdersController : Controller
    {
        private PharmacyDatabaseEntities9 db = new PharmacyDatabaseEntities9();

        // GET: Orders
        public ActionResult Index()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var orders = db.Orders.Include(o => o.Customer).Include(o => o.Medicine); 
                return View(orders.ToList());
            }
           
        }

        // GET: Orders/Details/5
        public ActionResult Details(int id)
        {
            return View(db.Orders.Where(x=>x.ord_id==id).FirstOrDefault());
           

        }

        // GET: Orders/Create
        public ActionResult Create()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {             
                ViewBag.cus_id = new SelectList(db.Customers, "cus_id", "firstname");
                ViewBag.med_id = new SelectList(db.Medicines, "med_id", "name");
                return View();
             }
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Orders.Add(order);
                order.total = order.quantity * order.unit_price;
                db.SaveChanges();
                return RedirectToAction("Index");
              
            }

            ViewBag.cus_id = new SelectList(db.Customers, "cus_id", "firstname", order.cus_id);
            ViewBag.med_id = new SelectList(db.Medicines, "med_id", "name", order.med_id);
            return View(order);
        }

        // GET: Orders/Edit/5
        public ActionResult Edit(int id)
        {
            Order order = new Order();
            ViewBag.cus_id = new SelectList(db.Customers, "cus_id", "firstname", order.cus_id);
            ViewBag.med_id = new SelectList(db.Medicines, "med_id", "name", order.med_id);
            return View(db.Orders.Where(x => x.ord_id == id).FirstOrDefault());

        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.cus_id = new SelectList(db.Customers, "cus_id", "firstname", order.cus_id);
            ViewBag.med_id = new SelectList(db.Medicines, "med_id", "name", order.med_id);
            return View(order);
        }

        // GET: Orders/Delete/5
        public ActionResult Delete(int id)
        {
            return View(db.Orders.Where(x=>x.ord_id==id).FirstOrDefault());

        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PharmacyManagementSystem/Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PharmacyManagementSystem.Models;

namespace PharmacyManagementSystem.Controllers
{
    public class RolesController : Controller
    {
        private PharmacyDatabaseEntities9 db = new PharmacyDatabaseEntities9();

        // GET: Roles
        public ActionResult Index()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {

                return View(db.Roles.ToList());
            }
        }

        // GET: Roles/Details/5
        public ActionResult Details(int id)
        {
            return View(db.Roles.Where(x=>x.role_id==id).FirstOrDefault());

        }

        // GET: Roles/Create
        public ActionResult Create()
        {
            if (Session["UserId"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                return View();
            }
        }

        // POST: Roles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Role role)
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }

        // GET: Roles/Edit/5
        public ActionResult Edit(int id)
        {
            return View(db.Roles.Where(x=>x.role_id==id).FirstOrDefault());
          
        }

        // POST: Roles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Role role)
        {
            if (ModelState.IsValid)
            {
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(role);
        }

        // GET: Roles/Delete/5
        public ActionResult Delete(int id)
        {
            return View(db.Roles.Where(x=>x.role_id==id).FirstOrDefault());

        }

        // POST: Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Role role = db.Roles.Find(id);
            db.Roles.Remove(role);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PharmacyManagementSystem/Views/Shared/_Layout.cshtml
@Html.Raw(TempData["LoginSuccessMessage"])

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DG PHARMA</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-dark" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom " style="color:white">DG PHARMA</div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Dashboard", "Index", "Home")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Customer", "Index", "Customers")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Role", "Index", "Roles")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Staff", "Index", "Staffs")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Medicine", "Index", "Medicines")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Category", "Index", "Categories")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Order", "Index", "Orders")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Supplier", "Index", "Suppliers")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Purchasing", "Index", "Purchasings")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" style="color:darkcyan" @Html.ActionLink("Report", "Index", "Reports")</a>



            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper ">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-expand-md border-bottom navbar-dark bg-dark navbar-fixed-top">
                <div class="container-fluid">
                   
                    <button class="navbar-toggler d-block" type="button" id="sidebarToggle">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="list-group-item-action p-3">@Html.ActionLink("About", "About", "Home", new { style = "color: darkcyan" })</li>
                        
                        </ul>
                        <br>
                        <hr />
                        <ul class="nav navbar-nav navbar-right" style="color:white">
                            @if (Session["UserId"] != null)
                            {
                                <h4 style="color:white"> Hello   @Session["UserName"]  </h4>
                                
                                <li class = " glyphicon glyphicon-log-out">
                                @Html.ActionLink("Logout", "Logout", "Login")
                                    </li>
                            }
                            else
                            {
                                @Html.ActionLink("Login", "Index", "Login")
                            }



                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                <h1 class="mt-4">Pharmacy Management System</h1>
                <p style="color:black">
                    This software stores detail of medicine purchase stock and sell stock.
                    We can maintain purchase stock detail by company wise sell stock detail by customer wise.
                    This software automated generate reports for stock,
                    sell, and customer detail.
                </p>
                <p>
                    @RenderBody()
                    @RenderSection("scripts", required: false)
                </p>

            </div>
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Content/js/scripts.js"></script>
    <div class="container body-content">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - All Rights Reserved | PharmacyManagementSystem</p>
        </footer>
    </div>
</body>
</html>

PharmacyManagementSystem/Views/Shared/_SidePanel_Layout.cshtml
@Html.Raw(TempData["LoginSuccessMessage"])

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>DG PHARMA</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/Content/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom ">DG PHARMA</div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Dashboard</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("About", "About", "Home")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Customer", "Index", "Customers")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Role", "Index", "Roles")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Staff", "Index", "Staffs")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Medicine", "Index", "Medicines")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Categorie", "Index", "Categories")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Order", "Index", "Orders")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Supplier", "Index", "Suppliers")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Purchasing", "Index", "Purchasings")</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" @Html.ActionLink("Report", "Index", "Reports")</a>


                
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper ">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-expand-md border-bottom navbar-dark bg-dark navbar-fixed-top">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle">Toggle Menu</button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item active"><a class="nav-link" href="#!">Home</a></li>
                            <li class="nav-item"><a class="nav-link" href="#!">Link</a></li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right" style="color:white">
                            @if (Session["UserId"] != null)
                            {
                                <h4 style="color:blue"> Hello @Session["UserName"]</h4>
                                @Html.ActionLink("Logout", "Logout", "Login")
                            }
                            else
                            {
                                @Html.ActionLink("Login", "Index", "Login")
                            }



                        </ul>
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                <h1 class="mt-4">Pharmacy Management System</h1>
                <p>This software stores detail of medicine purchase stock and sell stock.
                We can maintain purchase stock detail by company wise sell stock detail by customer wise. 
                This software automated generate reports for stock, 
                sell, and customer detail.</p>
                <p>
                 @RenderBody()
                 @RenderSection("scripts", required: false)
                </p>
                 
            </div>
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="~/Content/js/scripts.js"></script>
    <div class="container body-content">
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - All Rights Reserved | PharmacyManagementSystem</p>
        </footer>
    </div>
</body>
</html>